config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :restaurants do
    collection do
      get 'top', to: "restaurants#top"
    end
    resources :reviews, only: [ :new, :create ]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/restaurant.rb
class Restaurant < ApplicationRecord
  has_many :reviews, dependent: :destroy
  CATEGORIES = ["chinese", "italian", "japanese", "french", "belgian"]
  validates :name, presence: true
  validates :address, presence: true
  validates :phonenumber, presence: true
  validates :category, inclusion: { in: CATEGORIES }
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :restaurant
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController
  before_action :set_restaurant, only: [:show, :edit, :update, :destroy, :chef]


 def index
  @restaurants = Restaurant.all
end

def show
end

def new
  @restaurant = Restaurant.new(restaurant_params)
end

def edit
end

def update
    @restaurant.update(restaurant_params)
    redirect_to restaurant_path(@restaurant)
  end

def create
 @restaurant = Restaurant.new(restaurant_params)
 @restaurant.save
 redirect_to restaurant_path(@restaurant)
end

def destroy
  @restaurant.destroy
  redirect_to restaurants_path
end

def top
  @restaurants = Restaurant.where(stars: 3)
end

def chef
end

private

def restaurant_params
  params.require(:restaurant).permit(:name, :address, :description, :stars, :chef)
end

def set_restaurant
  @restaurant = Restaurant.find(params[:id])
end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/restaurants_helper.rb
module RestaurantsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>RailsYelpMvp</title>
  <%= csrf_meta_tags %>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">

  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
</head>

<body>
  <%= yield %>
</body>
</html>

app/views/restaurants/_form.html.erb
<%= form_for(@restaurant) do |f| %>
  <% if @restaurant.errors.any? %>
    <div id="error_explanation">
      <ul>
      <% @restaurant.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <!-- [...] all the fields -->
<% end %>

app/views/restaurants/destroy.html.erb
<h1>Effacer</h1>
<p>Find me in app/views/restaurants/destroy.html.erb</p>

app/views/restaurants/edit.html.erb
<h1>Editer un restaurant</h1>
<div class="container">
  <div class="row">
    <div class="col-xs-10 col-xs-offset-1">
      <%= simple_form_for @restaurant do |f| %>
      <%= f.label :name %>
      <%= f.text_field :name %>
      <%= f.label :description %>
      <%= f.text_area :description %>
      <%= f.label :chef %>
      <%= f.text_field :chef %>
      <%= f.label :stars %>
      <%= f.text_field :stars %>
      <%= f.button :submit %>
      <% end %>
    </div>
  </div>
   <%= link_to "retour", restaurants_path %>
</div>

app/views/restaurants/index.html.erb
<h1>Voici la liste des restaurants</h1>

<div class="container">
  <div class="row">
    <div class="col-xs-10 col-xs-offset-1">
      <ul class ="list_group">
        <% @restaurants.each do |restaurant| %>
        <li class="list-group-item">
          <h3><%= restaurant.name %></h3>
          <h3><%= restaurant.stars %>*</h3>
          <%= link_to "show", restaurant_path(restaurant) %>
          <%= link_to "edit", edit_restaurant_path(restaurant) %>
          <%= link_to "delete", restaurant_path(restaurant), method: :delete %>
        </li>
        <% end %>
      </ul>
    </div>
  </div>
</div>

app/views/restaurants/new.html.erb
<h1>Le nouveau restaurant</h1>
<div class="container">
  <div class="row">
    <div class="col-xs-10 col-xs-offset-1">
      <ul class ="list_group">
        <li class="list-group-item">
          <h3><%= @restaurant.name %></h3>
          <p><%= @restaurant.stars %>*</p>
          <%= link_to "index", restaurant_path(restaurant) %>
        </li>
        <% end %>
      </ul>
    </div>
  </div>
</div>

app/views/restaurants/show.html.erb
<h1>Restaurants#show</h1>
<p>Find me in app/views/restaurants/show.html.erb</p>

app/views/restaurants/top.html.erb
<h1>Voici la liste des meilleurs restaurants</h1>

<div class="container">
  <div class="row">
    <div class="col-xs-10 col-xs-offset-1">
      <ul class ="list_group">
        <% @restaurants.each do |restaurant| %>
        <li class="list-group-item">
          <h3><%= restaurant.name %></h3>
          <p><%= restaurant.stars %>*</p>
          <%= link_to "index", restaurant_path(restaurant) %>
        </li>
        <% end %>
      </ul>
    </div>
  </div>
</div>